services:
  db:
    container_name: planner-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - planner_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  planner_data:

networks:
  backend:
