name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies with pnpm
        run: pnpm install

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Run Format Check
        run: pnpm run format:check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Run Linting
        run: pnpm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        run: pnpm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: pnpm run test

  check-for-errors:
    name: Check for Errors
    needs: [lint, format, build, test]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: exit 1
